### ISSUE TITLE
Build error on actual branch of Azerothcore

### ISSUE THREAD

**Issue by PsYchoNauTek** [azerothcore/mod-1v1-arena#38] opened 2022-03-16 01:45 UTC
Module is giving some build errors with the latest version of [azerothcore:](https://github.com/azerothcore/azerothcore-wotlk/commit/e8d3292533c7e5d18af15d9bffabd581bacbadf9)
EDIT: last working version:
AzerothCore rev. 33635cbb3c83+ 2022-03-14 19:03:18 -0300 (master branch) (Win64, RelWithDebInfo, Static)

![image](https://user-images.githubusercontent.com/95944184/158497904-bfd09aa5-91b4-455b-b1a6-d3f18b912dfb.png)

**Comment by porkserver** [comment] 2022-03-17 18:26
I am also getting same error compiling on Debian 11.  It was compiling for me previously.  I am attaching the debug from my production server to show where it last worked for me.

`AC> AzerothCore rev. fd2a18a7554c+ 2022-03-07 00:46:01 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1k  25 Mar 2021 (library: OpenSSL 1.1.1k  25 Mar 2021)
Using Boost version: 1.74.0
Using MySQL version: 100512
Using CMake version: 3.18.4
Compiled on: Linux 5.10.0-11-amd64
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/gwilkins/Source/azcorebuild-archdruid/build/data/maps. Total size: 252191207 bytes
vmaps directory located in /home/gwilkins/Source/azcorebuild-archdruid/build/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/gwilkins/Source/azcorebuild-archdruid/build/data/mmaps. Total size: 2199390740 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: ACDB 335.6-dev
Using World DB Revision: 2022_03_07_00
Using Character DB Revision: 2022_03_01_00
Using Auth DB Revision: 2021_11_06_00
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-1v1-arena
- mod-archmage-timear
- mod-auto-revive
- mod-boss-announcer
- mod-eluna-lua-engine
- mod-guild-zone-system
- mod-new-character-perks
- mod-npc-enchanter
- mod-random-enchants
- mod-reward-played-time
- mod-skip-dk-starting-area
- mod-solo-lfg
- mod-solocraft
- mod-transmog`

**Comment by adink1** [comment] 2022-03-19 12:35
fatal error: no member named 'SetBgTypeIdAndArenaType' in 'BattlegroundQueue'

**Comment by porkserver** [comment] 2022-03-19 16:47
The updates to the Battlegroundqueue cpp broke this.  If you build off of a commit prior to 3/12/22 I think it will build successfully.  I am using on my production server currently.  
https://github.com/azerothcore/azerothcore-wotlk/commit/78bdc898813910c79c3a9c67f2bf9a0f1abef221

**Comment by Pholoween** [comment] 2022-03-23 15:33
> fatal error: no member named 'SetBgTypeIdAndArenaType' in 'BattlegroundQueue'

Same here... T-T

**Comment by Winfidonarleyan** [comment] 2022-03-23 17:54
i rework BG queue system, need rework module

**Comment by porkserver** [comment] 2022-03-23 18:05
Bogir has some patches that fix some items but we need to figure out hoe to adjust the mod to account for SetBgTypeIdAndArenaType being gone.  

Is there a renamed alternative for this function.  This is the last line of code not working.  I can do some testing if you have any suggestions.

**Comment by Bogir** [comment] 2022-03-24 04:39
Try this
I cant't test it ((
https://github.com/azerothcore/mod-1v1-arena/pull/39

**Comment by porkserver** [comment] 2022-03-24 21:00
It builds fine and works as intended until arena queue pops
When you select enter, nothing happens.  minimap icon gives option to port to said arena and also doesn't work.

**Comment by Rastrian** [comment] 2022-04-24 19:37
I'm working on a fix for this, but seems to be more than a arena creation bug.
When the arena end's the segfault happens.
![image](https://user-images.githubusercontent.com/10719452/164993433-26efed39-423d-4aa0-b39b-4760bd06a015.png)
![image](https://user-images.githubusercontent.com/10719452/164993468-ebe12744-d028-4788-b082-5b8ccb95f8cf.png)

**Comment by Rastrian** [comment] 2022-05-21 05:23
Found the solution, soon posting.
![image](https://user-images.githubusercontent.com/10719452/169636864-6ab183ab-d72b-4a45-8dd3-06e8fa900b69.png)

**Comment by Rastrian** [comment] 2022-05-21 18:24
@Helias please close this issue.

**Closed** 2022-05-21 18:32 UTC
