### ISSUE TITLE
Bug: Segmentation Fault

### ISSUE THREAD

**Issue by manstfu** [azerothcore/mod-1v1-arena#57] opened 2024-09-22 14:47 UTC
### Current Behaviour

https://gist.github.com/manstfu/b1a90e684d0fc72300e2939dcd732d0c

Im using commit https://github.com/XdevTLKWoW/1v1Module/commit/aef4b038bd55126a0fdd96239805f022d958d6da

### Expected Behaviour

/

### Steps to reproduce the problem

/

### AC rev. hash/commit

rev. 2e17b3250897

### Operating system

Debian 12

**Comment by Helias** [comment] 2024-09-22 15:15
Hi, I don't see any reference to the module in the crashdump, moreover I think that the link of the commit seems wrong.

Which azerothcore and mod-1v1-arena module are you using exactly_

**Comment by manstfu** [comment] 2024-09-22 17:22
in the crashdump it says
```
0x0000555557019f88 in typeinfo for **playerscript_1v1arena** ()
#0  0x0000555557019f88 in typeinfo for **playerscript_1v1arena** ()
```

not sure if that is associated with the module, i don't know how to reproduce it, i just find it in the gdb crashlog, i think it happened yesterday night.

Azerothcore rev. 2e17b3250897 https://github.com/azerothcore/azerothcore-wotlk/commit/2e17b3250897ec1fdf40840865245919410d1735

last update for 1v1 arena module was https://github.com/azerothcore/mod-1v1-arena/commit/aef4b038bd55126a0fdd96239805f022d958d6da

**Comment by Helias** [comment] 2024-09-22 21:05
I analyzed it but I still do not understand how they can be related.
I see that the issue is about "deleting a non-existing item in the guild bank", I am not 100% sure, but it does not seem related to playerscript_1v1arena, I see that is written in the log but I don't see the correlation.

**Comment by Helias** [comment] 2024-10-24 18:07
Recently I had a crashlog similar to this, but still I do not know how to reproduce it, @manstfu do you have any clue?

**Comment by manstfu** [comment] 2024-11-18 13:16
Yesterday crashed 2 times, in a 5 minute interval.. still can't reproduce :(

**Comment by manstfu** [comment] 2024-11-19 17:38
Yea, at the moment i have disabled it, waiting for other crashes to check if they are similar..

**Comment by Helias** [comment] 2024-11-30 11:29
it seems more of a generic issue that happens when the server crashes in general or it's manually closed.
I am closing the issue here because it's probably not related.
I did not experience this issue anymore in the chromiecraft server, so I think it's not related to this module

**Closed by Helias** 2024-11-30 11:29 UTC
